modLoader="javafml"
loaderVersion="[37,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="basalt_walker"
version="1.3.1"
displayName="Basalt Walker"
credits="Hashtag233"
displayURL="https://www.curseforge.com/minecraft/mc-mods/basalt-walker"
logoFile="logo.png"
authors="Hashtag233, MCreator"
description='''
New enchantment allows you to walk on lava.
'''

[[dependencies.basalt_walker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




