modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="basalt_walker"
version="1.2"
displayName="Basalt Walker"
credits="Hashtag233"
displayURL="https://www.curseforge.com/minecraft/mc-mods/basalt-walker"
logoFile="logo.png"
authors="Hashtatg233"
description='''
New enchantment allows you to walk on lava.
'''

[[dependencies.basalt_walker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




